/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class hoadon extends javax.swing.JFrame {

    /**
     * Creates new form hoadon
     */
    public hoadon() {
        initComponents();
    }
     private Connection connect = null;
    private JTable jtable = new JTable();
    private DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmahd = new javax.swing.JTextField();
        cbbmakh = new javax.swing.JComboBox<>();
        cbbmanv = new javax.swing.JComboBox<>();
        txtngaylap = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhd = new javax.swing.JTable();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\lisloaisanpham.png")); // NOI18N
        jLabel1.setText("BẢNG HÓA ĐƠN");

        jLabel2.setText("Mã Hóa Đơn:");

        jLabel3.setText("Mã KH:");

        jLabel4.setText("Mã NV:");

        jLabel5.setText("Năm Lập:");

        cbbmakh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbmanv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblhd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HD", "Tên KH", "Tên NV", "Năm Lập"
            }
        ));
        tblhd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhd);

        btnthem.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\Button-Add-icon.png")); // NOI18N
        btnthem.setText("Thêm");
        btnthem.setToolTipText("");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\pencil-red-icon.png")); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\Delete-icon.png")); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btnthoat.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\Button-Add-icon.png")); // NOI18N
        btnthoat.setText("Thêm Mới");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\lisloaisanpham.png")); // NOI18N
        jButton1.setText("Lập CT Hóa Đơn");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("D:\\Code\\Java\\JAVA-20210607T081428Z-001\\JAVA\\quanlydienmay\\Images\\exit.png")); // NOI18N
        jButton2.setText("Đóng Form");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbmanv, 0, 187, Short.MAX_VALUE)
                                    .addComponent(txtmahd)
                                    .addComponent(cbbmakh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtngaylap))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnthem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthoat))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnthem))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsua))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxoa)))
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        LayDuLieu();
        LayKH();
        LayNV();
        
    }//GEN-LAST:event_formWindowOpened

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        Main.playSound("music/soundbutton.wav");
        String mahd,maLoai,manv,ngaylap;
        mahd=txtmahd.getText();
        ngaylap=txtngaylap.getText();
        //
         Object [] obj = cbbmakh.getSelectedObjects();
        DisplayComboBoxModel item = (DisplayComboBoxModel) obj[0];
        maLoai = item.DisplayValue.toString();
        //
        Object [] abc = cbbmanv.getSelectedObjects();
        DisplayComboBoxModel atem = (DisplayComboBoxModel) abc[0];
        manv = atem.DisplayValue.toString();
        //
        String SQL = "insert into HOADON(mahd,makh,manv,ngaylaphd)"
                + " values('"+mahd+"','"+maLoai+"',"+manv+","+ngaylap+")";
        if("".equals(mahd) && "".equals(ngaylap) )
        {
            Main.thongBao("Bạn chưa nhập đầy đủ dữ liệu", "Thông Báo", 1);
        }
        else{
            Main.connection.ExcuteQueryUpdateDB(SQL);
            Main.thongBao("thêm dữ liệu thành công", "Thông Báo", 1);
        }
        LayDuLieu();
    }//GEN-LAST:event_btnthemActionPerformed

    private void tblhdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhdMouseClicked
        // TODO add your handling code here:
        Main.playSound("music/soundbutton.wav");
        int index = tblhd.getSelectedRow();
        txtmahd.setText(tblhd.getValueAt(index, 1).toString());
        String tenLoai = tblhd.getValueAt(index, 2).toString();
        String tenNV=tblhd.getValueAt(index, 3).toString();
        txtngaylap.setText(tblhd.getValueAt(index, 4).toString());
        setSelectedCombobox(tenLoai);
        setSelectedCombobox1(tenNV);
    }//GEN-LAST:event_tblhdMouseClicked

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        txtmahd.setText("");
        txtngaylap.setText("");
        cbbmakh.setSelectedIndex(0);
        cbbmanv.setSelectedIndex(0);
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        Main.playSound("music/soundbutton.wav");
        int[] index = tblhd.getSelectedRows();
        for(int i = 0; i < index.length; i++){
            String maCanXoa = tblhd.getValueAt(index[i], 1).toString();
            String SQL = "delete from HOADON where mahd = "+maCanXoa;
            Main.connection.ExcuteQueryUpdateDB(SQL);
            Main.thongBao("Xóa dữ liệu thành công", "Thông Báo", 1);
        }
        LayDuLieu();
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        String maSP,giaBan,maLoaiSP,manv;
        maSP = txtmahd.getText();
        giaBan = txtngaylap.getText();
        //
        Object [] obj = cbbmakh.getSelectedObjects();
        DisplayComboBoxModel item = (DisplayComboBoxModel) obj[0];
        maLoaiSP = item.DisplayValue.toString();
        //
        Object [] abc = cbbmanv.getSelectedObjects();
        DisplayComboBoxModel atem = (DisplayComboBoxModel) abc[0];
        manv = atem.DisplayValue.toString();
        try
        {
            String SQL = "update HOADON set ngaylaphd="+giaBan+", makh = "+maLoaiSP+", manv = "+manv+"WHERE mahd = "+txtmahd.getText();

            Main.connection.ExcuteQueryUpdateDB(SQL);
            LayDuLieu();
            Main.playSound("music/soundbutton.wav");
            Main.thongBao("Sửa dữ liệu thành công", "Thông Báo", 1);
        }
        catch (Exception ex)
        {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chitiethd cthd=new chitiethd();
        cthd.show();
        setVisible(false);
        Main.playSound("music/Emergency.wav");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);

        quanly ql=new quanly();
        ql.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        int kQ = JOptionPane.showConfirmDialog(null,
                "Bạn có muốn thoát chương trình không ?","Confirm",JOptionPane.YES_NO_OPTION);
        if(kQ == 0){
           Main.playSound("music/soundbutton.wav");
            System.exit(0);
        }else{
            
            Main.playSound("music/nonono.wav");
        }
    }//GEN-LAST:event_formWindowClosing
    private void LayDuLieu()
      {
        String SQL = "select * from HOADON";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(SQL);
        Object [] obj = new Object[]{"STT","Mã HD","Tên Khách Hàng","Tên Nhân Viên", "Năm LẬP"};
        DefaultTableModel tableModel = new DefaultTableModel(obj,0);
        tblhd.setModel(tableModel);
        try
        {
            while(rs.next())
            {
                Object [] item = new Object[10];
                item[0] = tblhd.getRowCount() + 1;
                item[1] = rs.getString("mahd");
                item[2] =layTenKH(rs.getString("makh"));
                item[3]=LayTenNV(rs.getString("manv"));
                item[4] = rs.getString("ngaylaphd");
                tableModel.addRow(item);
            }
        }
        catch (Exception ex)
        {
            System.out.println(ex.toString());
        }
    }
    private void setSelectedCombobox(String tenLoai)
    {
        
        for(int i = 0; i < cbbmakh.getItemCount(); i++)
        {
            Object obj = cbbmakh.getItemAt(i);
            
            if(obj != null)
            {
                DisplayComboBoxModel m = (DisplayComboBoxModel) obj;
                if(tenLoai.equals(m.DisplayMember))
                {
                    cbbmakh.setSelectedItem(m);
                }
            }        
        }    
    }
    private void setSelectedCombobox1(String tenNV)
    {
        for(int i = 0; i < cbbmanv.getItemCount(); i++)
        {
            Object obj = cbbmanv.getItemAt(i);
            
            if(obj != null)
            {
                DisplayComboBoxModel m = (DisplayComboBoxModel) obj;
                if(tenNV.equals(m.DisplayMember))
                {
                    cbbmanv.setSelectedItem(m);
                }
            }        
        }    
    }
    private String LayTenNV(String maNV)
    {
        String tenNV="";
        String url="select tennv from NHANVIEN where manv = "+maNV;
        ResultSet rs = Main.connection.ExcuteQueryGetTable(url);
        try{
            while(rs.next()){
                tenNV = rs.getString("tennv");
                return tenNV;
            }
        }
        catch (Exception e) {
            System.out.println("where?");
        }
         return tenNV;
    }
    private String layTenKH(String maLoai)
    {
        String manv=null;
         String tennv="";
        String tenLoai = "";
       
        String SQL = "select tenkh from KHACHHANG where makh = "+maLoai;
        ResultSet rs = Main.connection.ExcuteQueryGetTable(SQL);
        try{
            while(rs.next()){
                tenLoai = rs.getString("tenkh");
            }
        }
        catch (Exception e) {
            System.out.println("where?");
        }   
        return tenLoai;
       
    } 

    
   
   
    private void LayKH(){
       String SQL = "select * from KHACHHANG";
        ResultSet rs = Main.connection.ExcuteQueryGetTable(SQL);
        DefaultComboBoxModel cbbModel = new DefaultComboBoxModel();
        try{
           while(rs.next()){
               DisplayComboBoxModel item = new DisplayComboBoxModel(rs.getString("tenkh"), rs.getString("makh"));
               cbbModel.addElement(item);
           }
           cbbmakh.setModel(cbbModel);
        }
        catch (Exception e) {
            System.out.println("ở đây");
        }
        
    }
   private void LayNV()
   {
       String url = "select * from NHANVIEN";
        ResultSet ks = Main.connection.ExcuteQueryGetTable(url);
        DefaultComboBoxModel zxc = new DefaultComboBoxModel();
        try{
           while(ks.next()){
               DisplayComboBoxModel item = new DisplayComboBoxModel(ks.getString("tennv"), ks.getString("manv"));
               zxc.addElement(item);
           }
           cbbmanv.setModel(zxc);
        }
        catch (Exception e) {
            System.out.println("ở đây");
        }
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbbmakh;
    private javax.swing.JComboBox<String> cbbmanv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblhd;
    private javax.swing.JTextField txtmahd;
    private javax.swing.JTextField txtngaylap;
    // End of variables declaration//GEN-END:variables
}
